export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login',
    profile: '/auth/me',
  },
  compte: {
    get: '/personnes/me',
    update: '/personnes/me',
  },
  eleves: '/eleves',
  classes: '/classes',
  cycles: '/scolarite/cycles',
  salles: '/salles',
  inscriptions: '/annees/inscriptions',
  anneesAcademiques: '/annees',
  trimestres: '/annees/trimestres',
  matieres: '/cours',
  enseignants: '/cours/enseignants',
  evaluations: '/evaluations',
  notes: '/evaluations',
  incidents: '/parents/disciplines',
  sanctions: '/parents/rapports',
  modesPaiement: '/paiements/modes/list',
  tranches: '/scolarite/tranches',
  scolarites: '/scolarite',
  paiements: '/paiements',
  tuteurs: '/parents',
  quartiers: '/quartiers',
  villes: '/quartiers/villes',
  parents: '/parents',
  examens: '/evaluations/sessions',
  annonces: '/messages',
  transports: '/quartiers/residents',
  sauvegardes: '/healthz',
  absences: '/absences',
  abonnements: '/transport/abonnements',
  emploiDuTemps: '/cours/emploi-du-temps',
}
